# fly.toml app configuration file generated for nominas on 2023-10-18T22:12:17-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nominas"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
